### ISSUE TITLE
服务端能否将配置便携化保存在app目录

### ISSUE THREAD

**Issue by ttlttc** [vnt-dev/vnts#32]
现在保存在用户目录的 AppData\Roaming\com.example\vnt_app ,这个com.example是不是太随意了点...

**Comment by vnt-dev** [comment]
你能提pr吗，我改过这个好像没成功

**Comment by ttlttc** [comment]
发错了,应该发vntapp的

**Comment by vnt-dev** [comment]
是的，vntapp里的
